package fr.cyann.jinyparser.grammartree.analysis;/**
 * Copyright (C) 25/11/15 Yann Caron aka cyann
 * <p/>
 * Cette œuvre est mise à disposition sous licence Attribution -
 * Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 3.0 France.
 * Pour voir une copie de cette licence, visitez http://creativecommons.org/licenses/by-nc-sa/3.0/fr/
 * ou écrivez à Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
 **/

import fr.cyann.jinyparser.grammartree.GrammarElement;

/**
 * The BnfProcessor definition. Process the grammar tree and simplify links (remove nested links generated by LeftRecursionProcessor).
 */
public class LinkSimplificationProcessor implements AnalyseProcessor {

    @Override
    public GrammarElement analyse(GrammarElement root) {
        // loop on root and remove nested links.
/*
        for (GrammarElement element : root.depthFirstTraversal()) {
            if (element instanceof Link) {
                Link link = (Link)element;
                if (link.setRecursive())
            }
        }*/

        return root;

    }

}
